### ISSUE TITLE
1 typo, 1 correction

### ISSUE THREAD

**Issue by cregouby** [R-Toulouse/website#3]
Hello

https://github.com/R-Toulouse/website/blob/a8fb9057544f991389722dec22e12285906b524b/content/evenements/2022-12-07-rencontre-du-14-decembre-2022.Rmd#L17 a une typo à corriger par: 
```
**mercredi 14 décembre 2022** de **17h00 à 18h00**,  
```

https://github.com/R-Toulouse/website/blob/a8fb9057544f991389722dec22e12285906b524b/content/evenements/2022-12-07-rencontre-du-14-decembre-2022.Rmd#L37 peut être changé en : 
```
Cette présentation est une introduction au nouveau système de création de contenu présenté cet été par R Studio : **Quarto**, qui va révolutionner nos notebooks. Une petite histoire de ces derniers vous sera contée. On verra aussi comment cela se passe en pratique (Comment faire pour passer de Rmarkdown à Quarto ? Travailler avec plusieurs langages, c’est toujours possible ?) et on vous fera part de nos retours d’expérience. 
```

**Comment by gdevailly** [comment]
Merci Christophe !
Normalement c'est corrigé : [5a090100f245fd8204468262c467c653e7f0f89d](https://github.com/R-Toulouse/website/commit/5a090100f245fd8204468262c467c653e7f0f89d)
